### ISSUE TITLE
Type errors in readme demo (Python 3.5)

### ISSUE THREAD

**Issue by cx1111** [tompollard/tableone#6]
```
from tableone import TableOne
import pandas as pd

url="https://raw.githubusercontent.com/tompollard/data/master/primary-biliary-cirrhosis/pbc.csv"
data=pd.read_csv(url)
convars = ['time','age','bili','chol','albumin','copper',
       'alk.phos','ast','trig','platelet','protime']
catvars = ['status', 'ascites', 'hepato', 'spiders', 'edema',
       'stage', 'sex']
strat = 'trt'
nonnormal = ['bili']
mytable = TableOne(data, convars, catvars, strat, nonnormal)
mytable = TableOne(data, convars, catvars, strat, nonnormal, pval=True)
```

Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chen/Software/tableone/tableone.py", line 63, in __init__
    self._significance_table = self.__create_significance_table(data)
  File "/home/chen/Software/tableone/tableone.py", line 216, in __create_significance_table
    df.loc[v]['pval'],df.loc[v]['testname'] = self.__p_test(df,v,grouped_data,data)
  File "/home/chen/Software/tableone/tableone.py", line 266, in __p_test
    if min(min(observed)) < 5:
TypeError: unorderable types: dict_values() < dict_values()
```

**Comment by cx1111** [comment]
Next line:
`mytable.to_csv('mytable.csv')`

Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chen/Software/tableone/tableone.py", line 373, in to_csv
    writer.writerows(self.tableone)
TypeError: a bytes-like object is required, not 'str'

```

**Comment by tompollard** [comment]
Oh, testing in Python 3. This is set up to run on Python 2.7, so there will be bunch of changes needed to get running in 3.

**Comment by cx1111** [comment]
I see, sorry. Well demo works fine in 2.7.

**Comment by tompollard** [comment]
@cx1111 these should be fixed now. Please could you check?

**Comment by cx1111** [comment]
Looks good. Demo runs well.

**Comment by tompollard** [comment]
thanks Chen
